"""init_migration

Revision ID: 8ac3eabb894a
Revises: 
Create Date: 2021-10-17 16:01:20.551323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ac3eabb894a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.String(80), autoincrement=False, nullable=False),
    sa.Column('birthdate', postgresql.TIMESTAMP(timezone=False), autoincrement=False, nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', name='gender_type'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='pkey_profile'),
    sa.UniqueConstraint('user_name', name='profiles_user_name_key')
    )
    op.create_table('accounts',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(60), autoincrement=False, nullable=True),
    sa.Column('password', sa.String(500), autoincrement=False, nullable=True)
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(250), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('TRAINING', 'COMPETITION', name='run_type'), autoincrement=False, nullable=False),
    sa.Column('distance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('run_id', name='runs_run_id_key')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE gender')
    op.execute('DROP TYPE run_type')
    op.drop_table('runs')
    op.drop_table('profiles')
    op.drop_table('accounts')
    # ### end Alembic commands ###
